### ISSUE TITLE
Promote watershed delineation to AOI 1.0.8

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#554]
Fail to promote delineation to AOI with error Error Importing AOI : 'NoneType' object has no attribute 'name'

Also occurs when trying to promote to AOI from context.

**Comment by KellyMWhitehead** [comment]
Fixed for the upcoming release (1.0.8)

**Comment by joewheaton** [comment]
Seems like this is working in 1.0.9 for me.  Re-open @Jdgilby if you disagree.
